import { CarInputType } from '@view/components/track-page/panel/car-input/types';
import shuffle from './shuffle';

const carsData = [
  'Volkswagen Golf',
  'Renault Clio',
  'Volkswagen Polo',
  'Ford Fiesta',
  'Volkswagen Tiguan',
  'Nissan Qashqai',
  'Skoda Octavia',
  'Peugeot 208',
  'Ford Focus',
  'Citroen C3',
  'Renault Captur',
  'Opel Corsa',
  'Dacia Sandero',
  'Toyota Yaris',
  'Volkswagen Passat',
  'Peugeot 3008',
  'Dacia Duster',
  'Peugeot 2008',
  'Renault Mégane',
  'Skoda Fabia',
  'Fiat 500',
  'Ford Kuga',
  'Fiat Panda',
  'Opel Astra',
  'Peugeot 308',
  'Mercedes C Class',
  'Hyundai Tucson',
  'Audi A3',
  'Kia Sportage',
  'Seat Leon',
  'Kia Rio',
  'Audi A4',
  'Toyota C-HR',
  'Mercedes A Class',
  'Volkswagen T-Roc',
  'BMW 1 Series',
  'Mini',
  'Mercedes E Class',
  'Fiat Tipo',
  'Seat Ibiza',
  'Hyundai i20',
  'Toyota Auris',
  'BMW 3 Series',
  'Mercedes GLC',
  'Fiat 500x',
  'Renault Kadjar',
  'BMW X1',
  'BMW 5 Series',
  'Renault Scénic',
  'Toyota RAV4',
  'Ford Ecosport',
  'Opel Mokka',
  'Volkswagen Touran',
  'Skoda Rapid',
  'Volkswagen Up!',
  'Lada Vesta',
  'Kia Ceed',
  'Opel Crossland X',
  'Citroen C3 Aircross',
  'Mazda CX-5',
  'Renault Twingo',
  'Nissan Micra',
  'Toyota Aygo',
  'Nissan X-Trail',
  'Lada Granta',
  'Skoda Superb',
  'BMW 2 Series',
  'Volvo XC60',
  'Audi A6',
  'Suzuki Vitara',
  'Kia Picanto',
  'Jeep Renegade',
  'Hyundai i30',
  'Audi A1',
  'Audi Q2',
  'Peugeot 5008',
  'Seat Arona',
  'Opel Insignia',
  'Jeep Compass',
  'Hyundai i10',
  'Citroen C4 Picasso',
  'Audi Q3',
  'Seat Ateca',
  'Skoda Kodiaq',
  'Audi Q5',
  'Fiat 500L',
  'Nissan Juke',
  'Ford C-max',
  'Honda Civic',
  'Mercedes GLA',
  'Mercedes B Class',
  'Skoda Karoq',
  'Opel Grandland X',
  'Mercedes CLA',
  'Citroen C4 Cactus',
  'Peugeot 108',
  'Hyundai Creta',
  'Hyundai Solaris',
  'Audi A5',
  'Ford Mondeo',
];

const carGenerator = (
  amount = 100,
  cars: Array<string> = carsData
): Array<CarInputType> => {
  const copy = [...cars];
  return shuffle(copy)
    .slice(0, amount)
    .map((car) => {
      const color = String(Math.floor(Math.random() * 16777215).toString(16));
      return {
        name: car,
        color: `#${color === '000000' ? '111111' : color}`,
      };
    });
};

export default carGenerator;
